### ISSUE TITLE
Windows native extension support

### ISSUE THREAD

**Issue by subsoap** [sonountaleban/defold-luasec#1]
Could you add Windows support now that it has native extensions support?

https://github.com/sonountaleban/defold-crypto/blob/master/crypto/ext.manifest

Needs it too.

You should add britzl or other Defold team members as an admin of the repos so he can potentially do long term maintenance as your work is beginning to be used as dependencies in other projects.

**Comment by sonountaleban** [comment]
Hey, I'll do it as soon as possible.

**Comment by subsoap** [comment]
Glad to hear. Please add your work to here too when you can: https://www.defold.com/community/assets/

Contact Axel on Defold forum if you need images for the icons.

**Comment by sonountaleban** [comment]
Hi, about defold-crypto: I did a test and it should already work on Windows. Could you confirm this?

Cheers!

**Comment by subsoap** [comment]
Yes, can confirm defold-crypto on its own does build on Windows.

**Comment by sonountaleban** [comment]
Hey, finally I added the support for Windows native (x86 and x64). Let me know whether it works for you now, please.
